### ISSUE TITLE
Criar variáveis de ambiente

### ISSUE THREAD

**Issue by edibertooliveira** [paulogesualdo/api-car-rental#2]
*Segue link para auxiliar:* https://www.freecodecamp.org/portuguese/news/como-usar-variaveis-de-ambiente-do-node-com-um-arquivo-dotenv-para-node-js-e-npm/#:~:text=Como%20criar%20vari%C3%A1veis%20de%20ambiente,uma%20vari%C3%A1vel%20ao%20objeto%20process.

**Comment by paulogesualdo** [comment]
Feito, pull request: Feature/environment variables
