### ISSUE TITLE
Criar rota CRUD para 'cars' 

### ISSUE THREAD

**Issue by edibertooliveira** [paulogesualdo/api-car-rental#6]
##### Deve possuir
  name: string;
  brand: string;
  description: string;
  dailyRate: number;
  categoryId: string;
  available: boolean;
  licensePlate: string;

##### Deve ser criado um in-memory para simular metedos ORM de entidades

**Comment by paulogesualdo** [comment]
Vídeo sobre ORM Sequelize: https://www.youtube.com/watch?v=Fbu7z5dXcRs

**Comment by paulogesualdo** [comment]
Documentação do Postgrees para Node.js: https://node-postgres.com/

**Comment by paulogesualdo** [comment]
Documentação para utilizar o Postgres no Heroku: https://devcenter.heroku.com/articles/heroku-postgresql
